name: Sync Code

on:
  schedule:
    - cron: "0 * * * *"  # 每小时同步一次（实时性更强）
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    steps:
      - uses: actions/checkout@v3
      - uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: wenfxl/openai-cpa
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
